[package]
name = "pactyra-verifier"
version = "0.1.0"
description = "Objective verifier for Pyth price freshness"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "pactyra_verifier"

[features]
default = []
cpi = ["no-entrypoint"]
no-entrypoint = []
idl-build = ["anchor-lang/idl-build"]
test-sbf = []

[dependencies]
anchor-lang = { version = "0.31.1", features = ["init-if-needed"] }
pactyra-core = { path = "../pactyra-core", features = ["cpi"] }
